sudo: required

services:
  - docker

before_install:
  - docker build antimofeev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run antimofeev/react-test npm run test -- --coverage

after_success:
  - docker build -t antimofeev/multi-client ./client
  - docker build -t antimofeev/multi-nginx ./nginx
  - docker build -t antimofeev/multi-server ./server
  - docker build -t antimofeev/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push antimofeev/multi-client
  - docker push antimofeev/multi-nginx
  - docker push antimofeev/multi-server
  - docker push antimofeev/multi-worker